name: 'Enforce Code Owner Review'
description: 'Ensure that pull requests have required approvals from code owners.'
inputs:
  codeowners_path:
    description: 'Custom path to the CODEOWNERS file.'
    required: true
    default: '.github/CODEOWNERS'
  required_approvals:
    description: 'Number of required approvals from code owners.'
    required: true
    default: '2'
runs:
  using: 'node20'
  main: '../../index.js'